version: "3"
services:
  mongodb:
    image: mongo
    container_name: "mongodb"
    ports:
      - 27017:27017
  backend:
    image: backend
    container_name: "backend"
    ports:
      - 8080:8080
    environment:
      - MONGODB_URI=mongodb://mongodb
    depends_on:
      - mongodb